### ISSUE TITLE
Cleanup NetBeans license header for module java.navigation

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#101]
Review and cleanup the license header in java.navigation

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in java.navigation:
```
java.navigation/test/log.txt

```

**Comment by ghost** [comment]
There no header for this file java.navigation/test/log.txt

**Comment by emilianbold** [comment]
Hm, what might this file do? If it's just a developer note we might have to delete it.

**Comment by ghost** [comment]
I already searched around project but there is no use any where. That file just contains an **ant** command
So I think we should remove this file.

**Comment by emilianbold** [comment]
Yes, please remove it.

**Comment by emilianbold** [comment]
@trantuyen1505 will you make a PR for this?
