### ISSUE TITLE
Cleanup NetBeans license header for module java.project.ui

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#103]
Review and cleanup the license header in java.project.ui

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in java.project.ui:
```
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/AnnotationType.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Applet.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Class.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Empty.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Enum.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Exception.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Interface.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/JApplet.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Main.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Singleton.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/module-info.html
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/module-info.java.template
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/package-info.html
java.project.ui/src/org/netbeans/modules/java/project/ui/resources/package-info.java.template
java.project.ui/test/qa-functional/src/projects/apitest/CreateProjectTest.java
java.project.ui/test/qa-functional/src/projects/apitest/ProjectOpenListener.java
java.project.ui/test/qa-functional/src/projects/apitest/Utilities.java
java.project.ui/test/qa-functional/src/projects/libraries.properties
java.project.ui/test/qa-functional/src/projects/platforms.properties
java.project.ui/test/unit/data/simple-app/build.xml

```

**Comment by Sineth-N** [comment]
Hi @emilianbold, 
Would love to contribute ! and  I'm having a little doubt here, the license header text is same for all formats right ? No subtle changes in different file formats I believe ?

**Comment by emilianbold** [comment]
Look at pre-existing file to the license headers to copy-paste. Obviously a Java file and an XML file will have different types of comments / license headers.

Note that the .template files should probably be excluded from nbbuild/build.xml

**Comment by Sineth-N** [comment]
@emilianbold what I meant by 'same text' was, both .java and .xml files will carry the same 'content',
and .template files should be excluded in the nbbuild/build.xml as below right ?
`<exclude name="java.project.ui/src/org/netbeans/modules/java/project/ui/resources/*.template" />`

**Comment by emilianbold** [comment]
Yes, the 'content' is the Apache 2.0 license header. Please look at the other files and you'll see what I mean.

Exclusion seems about right.

**Comment by emilianbold** [comment]
@Sineth-N any interest in finishing this?

**Comment by steffendietz** [comment]
I would like to take over, if @Sineth-N has lost interrest. Just ping me. :+1:

**Comment by emilianbold** [comment]
Yes, it does seem like @Sineth-N has lost interest. Feel free to work on this one @steffendietz !
