### ISSUE TITLE
Cleanup NetBeans license header for module java.source

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#106]
Review and cleanup the license header in java.source

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in java.source:
```
java.source/apichanges.xml
java.source/src/org/netbeans/modules/java/resources/templates/Applet.template
java.source/src/org/netbeans/modules/java/resources/templates/Class.template
java.source/src/org/netbeans/modules/java/resources/templates/Empty.template
java.source/src/org/netbeans/modules/java/resources/templates/Exception.template
java.source/src/org/netbeans/modules/java/resources/templates/Interface.template
java.source/src/org/netbeans/modules/java/resources/templates/JApplet.template
java.source/src/org/netbeans/modules/java/resources/templates/Main.template
java.source/src/org/netbeans/modules/java/resources/templates/Package.template
java.source/src/org/netbeans/modules/java/source/Bundle.properties
java.source/src/org/netbeans/modules/java/source/resources/GeneratedMethodBody.template
java.source/src/org/netbeans/modules/java/source/resources/LambdaBody.template
java.source/src/org/netbeans/modules/java/source/resources/OverriddenMethodBody.template
java.source/test-excludes.txt
java.source/test/qa-functional/data/projects/default/build.xml
java.source/test/qa-functional/data/projects/default/src/org/netbeans/test/java/gui/copypaste/test2/empty.txt
java.source/test/qa-functional/data/projects/default/src/org/netbeans/test/java/gui/copypaste/test3/empty.txt
java.source/test/qa-functional/data/projects/default/src/org/netbeans/test/java/testsources/post/dummy
java.source/test/qa-functional/data/projects/default/test/Empty.java

```

**Comment by isalopez-zz** [comment]
Hi! Can I work on this?

**Comment by emilianbold** [comment]
All yours. Updated https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

**Comment by emilianbold** [comment]
@suvreial any update?

**Comment by steffendietz** [comment]
I could work on this in the evening. Would that be okay for you @suvreial?

**Comment by emilianbold** [comment]
@steffendietz please do
