### ISSUE TITLE
Cleanup NetBeans license header for module javadoc

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#108]
Review and cleanup the license header in javadoc

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in javadoc:
```
javadoc/test/unit/data/docs_jdk14_ja/api/index-files/index-4.title
javadoc/test/unit/src/org/netbeans/modules/javadoc/hints/AddTagFixTest.java

```

**Comment by ghost** [comment]
Working on

**Comment by ghost** [comment]
Done. PR #262

**Comment by emilianbold** [comment]
Could you investigate what index-4.title is supposed to be? Seems binary.

Maybe we need to exclude it in nbbuild/build.xml (rat task).

**Comment by ghost** [comment]
OK, I am going to investigate

**Comment by ghost** [comment]
It's just a file support for 2 test case in file javadoc/test/unit/src/org/netbeans/modules/javadoc/search/IndexBuilderTest.java
at line 141, 147.

So I am going to exclude it in nbbuild/build.xml (rat task).

**Comment by ghost** [comment]
Done. I have just excluded index-4.title in nbbuild/build.xml (rat task).
