### ISSUE TITLE
Cleanup NetBeans license header for module javahelp

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#113]
Review and cleanup the license header in javahelp

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in javahelp:
```
javahelp/src/org/netbeans/modules/javahelp/resources/favorites_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/helpset_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/helpset_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/index_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/index_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/map_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/map_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/toc_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/toc_2_0.dtd

```

**Comment by varaghar** [comment]
Working on this.
