### ISSUE TITLE
Cleanup NetBeans license header for module jellytools.ide

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#115]
Review and cleanup the license header in jellytools.ide

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in jellytools.ide:
```
jellytools.ide/test/qa-functional/data/SampleProject/build.xml
jellytools.ide/test/qa-functional/data/SampleProject/src/sample1/html.html
jellytools.ide/test/qa-functional/data/SampleProject/src/sample1/properties.properties
jellytools.ide/test/qa-functional/data/SampleProject/src/sample1/unrecognized
jellytools.ide/test/qa-functional/data/SampleProject/src/sample1/url.url

```

**Comment by evilris** [comment]
Working on it 👍

**Comment by emilianbold** [comment]
Sure!

**Comment by emilianbold** [comment]
@evilris any update?

**Comment by steffendietz** [comment]
This module seems no longer to be included in the `rat` report.

The previously reported files are now excluded based on:
https://github.com/emilianbold/incubator-netbeans/blob/cc33dff96198b845b55aa4f3f9da4ad6f627a174/nbbuild/build.xml#L1995

**Comment by emilianbold** [comment]
Thank you.
