### ISSUE TITLE
Cleanup NetBeans license header for module jshell.support

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#119]
Review and cleanup the license header in jshell.support

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in jshell.support:
```
jshell.support/src/org/netbeans/modules/jshell/project/Bundle.properties
jshell.support/src/org/netbeans/modules/jshell/resources/ShellClass.java.template
jshell.support/src/org/netbeans/modules/jshell/resources/consoleExample.jsh
jshell.support/src/org/netbeans/modules/jshell/tool/Feedback.java
jshell.support/test/unit/src/org/netbeans/modules/jshell/support/reploutput.txt
jshell.support/test/unit/src/org/netbeans/modules/jshell/support/reploutput_golden.txt

```

**Comment by michael-simons** [comment]
I'll take this one.

**Comment by emilianbold** [comment]
All yours! And welcome!

**Comment by emilianbold** [comment]
BTW:

>I did not change
> jshell.support/test/unit/src/org/netbeans/modules/jshell/support/reploutput.txt
> jshell.support/test/unit/src/org/netbeans/modules/jshell/support/reploutput_golden.txt
> as I think that this will break tests.

Maybe these would have to be excluded in nbbuild/build.xml (ant rat task)?

> I did not change
> jshell.support/src/org/netbeans/modules/jshell/resources/consoleExample.jsh
> as I don't know how that template is used and what format a comment must have.

Maybe exclude it too?
