### ISSUE TITLE
Cleanup NetBeans license header for module languages

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#126]
Review and cleanup the license header in languages

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in languages:
```
languages/test/qa-functional/data/OpenFileProj/build.xml
languages/test/qa-functional/data/OpenFileProj/src/files/sample.bat
languages/test/qa-functional/data/OpenFileProj/src/files/sample.diff
languages/test/qa-functional/data/OpenFileProj/src/files/sample.mf
languages/test/qa-functional/data/tokens/sample.bat
languages/test/qa-functional/data/tokens/sample.diff
languages/test/qa-functional/data/tokens/sample.mf

```

**Comment by phinaliumz** [comment]
Working on this.

**Comment by emilianbold** [comment]
Closing this since `*/test/qa-functional/data/**` is excluded globally so this module doesn't trigger any Rat warning anymore.
