### ISSUE TITLE
Cleanup NetBeans license header for module localhistory

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#140]
Review and cleanup the license header in localhistory

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in localhistory:
```
localhistory/test/qa-functional/data/JavaApp/build.xml

```

**Comment by mohammedalics** [comment]
This file is automatically generated therefor no Oracle license.

As mentioned: 
You may freely edit this file. See commented blocks below for 
some examples of how to customize the build. -
(If you delete it and reopen the project it will be recreated.)

**Comment by emilianbold** [comment]
Thanks!
