### ISSUE TITLE
Cleanup NetBeans license header for module maven.model

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#144]
Review and cleanup the license header in maven.model

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in maven.model:
```
maven.model/test/unit/src/profiles.xml
maven.model/test/unit/src/settings.xml

```

**Comment by batouxclass** [comment]
could I work on this issue ?

**Comment by emilianbold** [comment]
All yours. Updated https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

**Comment by emilianbold** [comment]
Sorry, it seems somebody did a PR upstream about this https://github.com/apache/incubator-netbeans/pull/160

https://lists.apache.org/thread.html/f735dcb54f379d07ef25d2e62c3c6649c648ac614f51366d3b626a35@%3Cdev.netbeans.apache.org%3E

**Comment by batouxclass** [comment]
ok, don't worry.

**Comment by rosslamont** [comment]
Sorry about that!
