### ISSUE TITLE
Cleanup NetBeans license header for module projectimport.eclipse.core

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#174]
Review and cleanup the license header in projectimport.eclipse.core

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in projectimport.eclipse.core:
```
projectimport.eclipse.core/test/createWorkspace.sh
projectimport.eclipse.core/test/unit/data/180876.classpath
projectimport.eclipse.core/test/unit/data/71770.classpath
projectimport.eclipse.core/test/unit/data/91669.classpath
projectimport.eclipse.core/test/unit/data/JSFLibraryRegistryV2.xml
projectimport.eclipse.core/test/unit/data/external-source-roots.classpath
projectimport.eclipse.core/test/unit/data/external-source-roots.project
projectimport.eclipse.core/test/unit/data/org.eclipse.wst.common.project.facet.core.xml

```

**Comment by markhobson** [comment]
I'll take this, thanks.

**Comment by emilianbold** [comment]
Reserved for you.
