### ISSUE TITLE
Cleanup NetBeans license header for module projectui

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#175]
Review and cleanup the license header in projectui

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in projectui:
```
projectui/src/org/netbeans/modules/project/ui/resources/license-default.txt

```

**Comment by varaghar** [comment]
Working on

**Comment by tomazst** [comment]
Can I take this?

**Comment by emilianbold** [comment]
I suspect this doesn't need a header, but an exclude in build.xml

**Comment by emilianbold** [comment]
But otherwise, it's all yours. Please investigate if the file is user-visible or not.

**Comment by tomazst** [comment]
Why this files are not included in this issue? Why don't we exclude them from rat?
projectui/src/org/netbeans/modules/project/ui/resources/bsd-license.txt
projectui/src/org/netbeans/modules/project/ui/resources/epl10-license.txt
projectui/src/org/netbeans/modules/project/ui/resources/explorer-override.wsmode
projectui/src/org/netbeans/modules/project/ui/resources/gpl20-license.txt
projectui/src/org/netbeans/modules/project/ui/resources/gpl30-license.txt
projectui/src/org/netbeans/modules/project/ui/resources/lgpl21-license.txt
projectui/src/org/netbeans/modules/project/ui/resources/mit-license.txt

**Comment by emilianbold** [comment]
I'm not sure why they were not picked up. They should also be excluded from Rat in build.xml.

**Comment by emilianbold** [comment]
Note that "*.wsmode" is a problem to be solved centrally https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

I'm talking about excluding the -license.txt files.

**Comment by tomazst** [comment]
I excluded all license files.
