### ISSUE TITLE
Cleanup NetBeans license header for module properties.syntax

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#177]
Review and cleanup the license header in properties.syntax

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in properties.syntax:
```
properties.syntax/src/org/netbeans/modules/properties/syntax/PropertiesExample

```

**Comment by vpondala** [comment]
There is no license header in PropertiesExample.

**Comment by emilianbold** [comment]
We should add license headers even to empty files. Still, if it's an user-facing template we should not.

So -- what is this file? Could you perhaps look where it is being used?

**Comment by steffendietz** [comment]
Is this still worked on @vpondala? Else I would take over?

**Comment by emilianbold** [comment]
It doesn't seem like @vpondala is working on it. @steffendietz, do you want to add the file to the nbbuild/build.xml "rat" exclusion list?

**Comment by steffendietz** [comment]
Yes. The mentioned file is used as an example for the "properties" language in the "Fonts & Colors" option Tab.
