### ISSUE TITLE
Cleanup NetBeans license header for module properties

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#178]
Review and cleanup the license header in properties

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in properties:
```
properties/src/org/netbeans/modules/properties/sample.properties.template
properties/test/qa-functional/data/projects/properties_test/build.xml
properties/test/qa-functional/data/projects/properties_test/src/examples/testPropertiesFile.properties
properties/test/qa-functional/data/projects/properties_test/src/samples/testPropertiesFile.properties
properties/test/qa-functional/data/projects/properties_test2/build.xml
properties/test/qa-functional/data/projects/properties_test2/src/example/testPropertiesFile.properties

```

**Comment by dealton** [comment]
starting on it

**Comment by dealton** [comment]
What is your threshold for whether a file gets a license header.

**Comment by emilianbold** [comment]
Read up on https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review
and http://www.apache.org/legal/src-headers.html#faq-exceptions

Maybe even join the dev@ mailing list if you want to talk about it.

For this particular module I would exclude everything (the template and the test data) via nbbuild/build.xml ("rat" task). So I wouldn't add any license header.

**Comment by steffendietz** [comment]
Hi. Is this still free? I would take a stab at this.

**Comment by emilianbold** [comment]
All yours.

**Comment by emilianbold** [comment]
Updated https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

**Comment by steffendietz** [comment]
After running the `rat` again, it seems that only
```
properties/src/org/netbeans/modules/properties/sample.properties.template
```
is still reported as problematic.

Can you confirm @emilianbold?

Since this file is used as a base template, I would add it to the exclude list without adding license information.
