### ISSUE TITLE
Cleanup NetBeans license header for module spi.navigator

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#191]
Review and cleanup the license header in spi.navigator

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in spi.navigator:
```
spi.navigator/apichanges.xml
spi.navigator/test/unit/src/org/netbeans/modules/navigator/resources/lastsel/file.lastsel_mime1

```

**Comment by trantuyen1505** [comment]
Working on

**Comment by mohammedalics** [comment]
working on it.

**Comment by mohammedalics** [comment]
File spi.navigator/test/unit/src/org/netbeans/modules/navigator/resources/lastsel/file.lastsel_mime1
is empty. I can add license header if needed

**Comment by emilianbold** [comment]
If it's empty then perhaps we can exclude it. See nbbuild/build.xml ("rat" task)

**Comment by mohammedalics** [comment]
ok, so I'll add exclude for this file in rat file.

**Comment by mohammedalics** [comment]
Done [PR#255 ](https://github.com/emilianbold/incubator-netbeans/pull/255)
