### ISSUE TITLE
Cleanup NetBeans license header for module spi.viewmodel

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#193]
Review and cleanup the license header in spi.viewmodel

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in spi.viewmodel:
```
spi.viewmodel/src/org/netbeans/spi/viewmodel/package.html

```

**Comment by mihaivpopescu** [comment]
Working on this.

**Comment by batouxclass** [comment]
I'm going to work on this one.

**Comment by emilianbold** [comment]
@ArkantosC did you comment at the same time with @mihaivpopescu?

@mihaivpopescu: please pick another issue, there's plenty more. I see @ArkantosC is already trying to make a PR.

**Comment by mihaivpopescu** [comment]
Sure

**Comment by batouxclass** [comment]
I'm sorry @mihaivpopescu, looks like I wrote the comment at the same time.
