### ISSUE TITLE
Cleanup NetBeans license header for module templates

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#197]
Review and cleanup the license header in templates

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in templates:
```
templates/src/org/netbeans/modules/templates/resources/userprop.txt

```

**Comment by 38leinaD** [comment]
done https://github.com/emilianbold/incubator-netbeans/pull/242

**Comment by emilianbold** [comment]
This remark from https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review is good:

>  userprop.txt is an user-facing template file, it cannot be created by default with the license block.

userprop.txt should actually be excluded from rat. See nbbuild/build.xml, the target "rat" and add another exception with `exclude`

Sorry you had to to the PR before I got to look into it.

**Comment by 38leinaD** [comment]
ok, i updated the pull request; added the exclusion. put it in with absolute path because i did not find any other occurences of a userprop.txt in the codebase.

**Comment by emilianbold** [comment]
Absolute path is perfect.
