### ISSUE TITLE
Cleanup NetBeans license header for module terminal

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#198]
Review and cleanup the license header in terminal

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in terminal:
```
terminal/README.attributes
terminal/README.close_semantics

```

**Comment by chizoba** [comment]
started

**Comment by 38leinaD** [comment]
So, these seem to be readme files. The a guide states 

> Other files may make sense to have no license header. Three examples are:
> "Short informational text files; for example README, INSTALL files. The expectation is that these files make it obvious which product they relate to."

So, i assume nothing needs to be added here? Or should the liense header be added anyway?

**Comment by emilianbold** [comment]
Yes, if you look at https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review it seems junichi11 looked into this module already.

But they don't seem 'short' to me. Particularly README.close_semantics seems to have some meat.

So I'd rather add the license header to these too.

**Comment by 38leinaD** [comment]
it seems like this effort here with the hacktoberfest issues is not well organized with the offical contributors; otherwise i don't understand why two people work on the same issue...
so, i assume we can close this issue here?

**Comment by emilianbold** [comment]
Well, I auto-generated 225 hacktoberfest issues based on the ant rat output.

The issue on https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review is not finished since these files still remain and they were not excluded so... they were picked up again.

I still believe that those two files need license headers but we can close this.
