### ISSUE TITLE
Cleanup NetBeans license header for module testng.ui

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#201]
Review and cleanup the license header in testng.ui

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in testng.ui:
```
testng.ui/src/org/netbeans/modules/testng/ui/resources/EmptyTestNGTest.java.template
testng.ui/src/org/netbeans/modules/testng/ui/resources/TestNGSuite.xml.template
testng.ui/src/org/netbeans/modules/testng/ui/wizards/Bundle.properties

```

**Comment by trevlewis** [comment]
Working on

**Comment by trevlewis** [comment]
PR https://github.com/emilianbold/incubator-netbeans/pull/247

**Comment by emilianbold** [comment]
What about the *.template files?

**Comment by trevlewis** [comment]
They did not have license headers in place.

**Comment by trevlewis** [comment]
I only updated files that had a license header in place that I could just replace. If you want me to add the license header when it is not present in a file just let me know.

**Comment by emilianbold** [comment]
The description tries to explain this:

>For an empty file that supports headers you must add the Apache license header.

It should have said:

>For a file without a license header that supports headers you must add the Apache license header.

So yes, if it's not minor (see http://www.apache.org/legal/src-headers.html#faq-exceptions ) they must be added.

**Comment by trevlewis** [comment]
Okay. I will go through and add them.

**Comment by trevlewis** [comment]
@emilianbold I looked at 15-20 other template files and I found none that have the license in them, even though they mention the license like EmptyTestNGTest.java.template does. Do you have a specific example that does this?

**Comment by emilianbold** [comment]
Then we must exclude them in build.xml?

**Comment by trevlewis** [comment]
That makes sense. Just wanted to make sure I wasn't missing a template file that did what you where asking for.

**Comment by emilianbold** [comment]
I also did a build and it seemed to me the template header would be visible via Tools | Templates , Open in Editor so we don't want that. If it's not user-visible we add it in.

Right now I'd say to just exclude the *.template files.
