### ISSUE TITLE
Cleanup NetBeans license header for module utilities

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#204]
Review and cleanup the license header in utilities

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in utilities:
```
utilities/src/org/netbeans/modules/utilities/netbeans-kb.url
utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/File1.txt
utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/File2.blabla
utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/File3.html

```

**Comment by 38leinaD** [comment]
Only contains a url:
utilities/src/org/netbeans/modules/utilities/netbeans-kb.url

These files are empty:
utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/File1.txt
utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/File2.blabla
utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/File3.html

I assume there is nothing to be done here.

**Comment by emilianbold** [comment]
Then we should exclude utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/* from rat. See nbbbuild/build.xml

I see we have about 14 .url files in the repository, we should probably exclude those from rat too.

**Comment by 38leinaD** [comment]
Ok, i excluded from rat: utilities/test/unit/src/org/netbeans/modules/openfile/resources/recent_files/*

Also, added general rule for url-files that should capture all of these:
./utilities/src/org/netbeans/modules/utilities/netbeans-kb.url
./welcome/src/org/netbeans/modules/welcome/resources/community.url
./welcome/src/org/netbeans/modules/welcome/resources/tour.url
./welcome/src/org/netbeans/modules/welcome/resources/tutorial1-1.url
./welcome/src/org/netbeans/modules/welcome/resources/tutorial1.url
./welcome/src/org/netbeans/modules/welcome/resources/tutorial2.url
./welcome/src/org/netbeans/modules/welcome/resources/tutorial3.url
./welcome/src/org/netbeans/modules/welcome/resources/tutorial4.url
./welcome/src/org/netbeans/modules/welcome/resources/tutorial5.url
./welcome/src/org/netbeans/modules/welcome/resources/whatsnew.url
./jellytools.ide/test/qa-functional/data/SampleProject/src/sample1/url.url
./jellytools.java/test/qa-functional/data/SampleProject/src/sample1/url.url
./jellytools.platform/test/qa-functional/data/SampleProject/src/sample1/url.url
./java.examples/src/org/netbeans/modules/java/examples/resources/GUIExamplesDescription.url

pullrequest is created: https://github.com/emilianbold/incubator-netbeans/pull/254
