### ISSUE TITLE
Cleanup NetBeans license header for module versioning.core

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#205]
Review and cleanup the license header in versioning.core

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in versioning.core:
```
versioning.core/test/qa-functional/data/tck.properties.template
versioning.core/test/unit/data/workdir/root-test-versioned/a.txt
versioning.core/test/unit/data/workdir/root-test-versioned/b-test-versioned/b.txt
versioning.core/test/unit/data/workdir/root-with-exclusions/folder/excl/newfile
versioning.core/test/unit/data/workdir/root-with-exclusions/folder/newfile
versioning.core/test/unit/data/workdir/root-with-exclusions/newfile
versioning.core/test/unit/data/workdir/root-with-exclusions/subfolder-excl/file
versioning.core/test/unit/data/workdir/root/a.txt

```

**Comment by trevlewis** [comment]
Working on.

**Comment by trevlewis** [comment]
No license headers present in these files.

**Comment by emilianbold** [comment]
versioning.core/test/qa-functional/data/tck.properties.template seems like it might handle a license header.

The rest of the test files look like they might need to be excluded from the license check. Exclude them via nbbuild/build.xml ("rat" target).

**Comment by trevlewis** [comment]
There isn't a license header in it right now. I can add one if you would like.

**Comment by trevlewis** [comment]
~~PR https://github.com/emilianbold/incubator-netbeans/pull/299~~

@emilianbold How does this look? Not sure if I need to exclude each file or sub directory or is how I did it fine? Seems to be a mix of ways it is already done.

**Comment by trevlewis** [comment]
New PR https://github.com/emilianbold/incubator-netbeans/pull/301
