### ISSUE TITLE
Cleanup NetBeans license header for module versioning

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#207]
Review and cleanup the license header in versioning

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in versioning:
```
versioning/test/qa-functional/data/tck.properties.template
versioning/test/unit/data/workdir/root-test-versioned/a.txt
versioning/test/unit/data/workdir/root-test-versioned/b-test-versioned/b.txt
versioning/test/unit/data/workdir/root-with-exclusions/folder/excl/newfile
versioning/test/unit/data/workdir/root-with-exclusions/folder/newfile
versioning/test/unit/data/workdir/root-with-exclusions/newfile
versioning/test/unit/data/workdir/root-with-exclusions/subfolder-excl/file
versioning/test/unit/data/workdir/root/a.txt

```

**Comment by trevlewis** [comment]
Working on.

**Comment by trevlewis** [comment]
These files actually have nothing in them:

versioning/test/unit/data/workdir/root-test-versioned/b-test-versioned/b.txt
versioning/test/unit/data/workdir/root-with-exclusions/folder/excl/newfile
versioning/test/unit/data/workdir/root-with-exclusions/folder/newfile
versioning/test/unit/data/workdir/root-with-exclusions/newfile
versioning/test/unit/data/workdir/root-with-exclusions/subfolder-excl/file

**Comment by trevlewis** [comment]
PR https://github.com/emilianbold/incubator-netbeans/pull/239

**Comment by emilianbold** [comment]
> These files actually have nothing in them:

Maybe they need to be excluded from `ant rat`.
