### ISSUE TITLE
Cleanup NetBeans license header for module web.common

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#208]
Review and cleanup the license header in web.common

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in web.common:
```
web.common/src/org/netbeans/modules/web/common/api/mime.types
web.common/test/unit/data/folder/inner.folder/fourth.txt
web.common/test/unit/data/folder/innerfolder/fourth.txt
web.common/test/unit/data/folder/innerfolder2/fifth.txt
web.common/test/unit/data/folder/second.txt
web.common/test/unit/data/one.txt
web.common/test/unit/data/sourcemaps/greeter.dmapping
web.common/test/unit/data/sourcemaps/greeter.imapping
web.common/test/unit/data/sourcemaps/greeter.js
web.common/test/unit/data/sourcemaps/greeter.js.map
web.common/test/unit/data/sourcemaps/test_1.map
web.common/test/unit/data/space issue229522/test.css
web.common/test/unit/data/third.txt
web.common/web.common.webloc

```

**Comment by tomazst** [comment]
I'll take this.

**Comment by emilianbold** [comment]
Sorry, according to https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review vikas.prabhakar is doing this.

Please select another issue.

**Comment by tomazst** [comment]
OK.
