### ISSUE TITLE
Cleanup NetBeans license header for module web.webkit.debugging

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#209]
Review and cleanup the license header in web.webkit.debugging

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in web.webkit.debugging:
```
web.webkit.debugging/src/org/netbeans/modules/web/webkit/debugging/api/css/Longhands.txt

```

**Comment by trevlewis** [comment]
Working on

**Comment by trevlewis** [comment]
This file currently does not have a license header in it. I can add the Short Form if you think it is needed.

**Comment by emilianbold** [comment]
Hm, seems like it should be excluded. Not sure how it's parsed.

**Comment by emilianbold** [comment]
Thanks for looking into it, closing.
