### ISSUE TITLE
Cleanup NetBeans license header for module beans

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#21]
Review and cleanup the license header in beans

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in beans:
```
beans/src/org/netbeans/modules/beans/resources/templates/AddProperty.freemarker
beans/src/org/netbeans/modules/beans/resources/templates/Bean.java.template
beans/src/org/netbeans/modules/beans/resources/templates/BeanInfo.java.template
beans/src/org/netbeans/modules/beans/resources/templates/Customizer.form.template
beans/src/org/netbeans/modules/beans/resources/templates/Customizer.java.template
beans/src/org/netbeans/modules/beans/resources/templates/NoIconBeanInfo.java.template
beans/src/org/netbeans/modules/beans/resources/templates/PropertyEditor.java.template
beans/test/qa-func/src/gui/data/TestFile.java
beans/test/qa-functional/data/projects/Beans/build.xml
beans/test/qa-functional/data/projects/Beans/src/beans/Add.java
beans/test/qa-functional/data/projects/Beans/src/beans/AddBeanInfo.java
beans/test/qa-functional/data/projects/Beans/src/beans/Beans.java
beans/test/qa-functional/data/projects/Beans/src/beans/Generate.java
beans/test/qa-functional/data/projects/Beans/src/beans/Source.java
beans/test/qa-functional/data/projects/Beans/src/beans/SourceBeanInfo.java
beans/test/qa-functional/data/projects/Beans/src/members/Test_A_A.java

```

**Comment by bjansen** [comment]
On it.

**Comment by bjansen** [comment]
I think all the `*.template` file don't need any header, because they would also be visible when users edit those templates (like in #276). I'll add them to the rat exlude list.

**Comment by emilianbold** [comment]
Yes, please do. We can always revert the exclusion if Apache really wants that header.
