### ISSUE TITLE
Cleanup NetBeans license header for module websvc.saas.codegen.java

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#211]
Review and cleanup the license header in websvc.saas.codegen.java

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in websvc.saas.codegen.java:
```
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/Bundle.properties
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/ApiKeyAuthenticator.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/HttpBasicAuthenticator.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/RestConnection.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/RestResponse.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/SaasService.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/SessionKeyAuthenticator.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/SignedUrlAuthenticator.template
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/apikey.properties
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/httpbasic.properties
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/sessionkey.properties
websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/resources/signedurl.properties

```

**Comment by tomazst** [comment]
Can I take this?

**Comment by emilianbold** [comment]
All yours. Updated https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review for websvc.saas.codegen.java

**Comment by emilianbold** [comment]
Hacktoberfest over. Good job everybody!
