### ISSUE TITLE
Cleanup NetBeans license header for module websvc.saas.kit

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#213]
Review and cleanup the license header in websvc.saas.kit

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in websvc.saas.kit:
```
websvc.saas.kit/release/VERSION.txt

```

**Comment by trevlewis** [comment]
Working on.

**Comment by emilianbold** [comment]
Hm, not sure websvc.saas.kit/release/VERSION.txt needs a license header.

**Comment by trevlewis** [comment]
It doesn't have one currently, but I could put the Short Form in there if you would like.

"Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements; and to You under the Apache License, Version 2.0. "

**Comment by emilianbold** [comment]
I'm not entirely certain what that file is supposed to do... or if we even need it.

Might be simpler to exclude it in nbbuild/build.xml ("rat" task)

**Comment by trevlewis** [comment]
Okay. I will do that then.

**Comment by trevlewis** [comment]
PR https://github.com/emilianbold/incubator-netbeans/pull/302
