### ISSUE TITLE
Cleanup NetBeans license header for module xml.jaxb

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#219]
Review and cleanup the license header in xml.jaxb

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in xml.jaxb:
```
xml.jaxb/src/org/netbeans/modules/xml/jaxb/CodeTemplates.xml
xml.jaxb/src/org/netbeans/modules/xml/jaxb/layer.xml
xml.jaxb/src/org/netbeans/modules/xml/jaxb/ui/Bundle.properties
xml.jaxb/test/qa-functional/data/CreditReport.xsd
xml.jaxb/test/qa-functional/data/CreditReportSimple.wsdl
xml.jaxb/test/qa-functional/data/toc_2_0.dtd
xml.jaxb/test/unit/src/data/BuildFile1.xml
xml.jaxb/test/unit/src/data/BuildFile2.xml
xml.jaxb/test/unit/src/data/BuildFile3.xml
xml.jaxb/test/unit/src/data/BuildFileEmptyCatalog.xml
xml.jaxb/test/unit/src/data/ConfigFile1.xml
xml.jaxb/test/unit/src/data/ConfigFile2.xml
xml.jaxb/test/unit/src/data/ConfigFile3.xml
xml.jaxb/test/unit/src/data/ConfigFileEmptyCatalog.xml

```

**Comment by mirkoperillo** [comment]
Hi @emilianbold I can help on this

**Comment by emilianbold** [comment]
I believe @gravitydestroyer is working on this in https://github.com/emilianbold/incubator-netbeans/pull/3

Please pick something else.

**Comment by mirkoperillo** [comment]
Ok

**Comment by emilianbold** [comment]
@mirkoperillo did you pick anything else? There are still a few nice ones open.

**Comment by mirkoperillo** [comment]
@emilianbold if you can suggest me a not assigned issue I can give you a hand

**Comment by emilianbold** [comment]
@mirkoperillo https://github.com/emilianbold/incubator-netbeans/issues/86 is nice. Assigning it to you.

**Comment by emilianbold** [comment]
Hacktoberfest over
