### ISSUE TITLE
Cleanup NetBeans license header for module css.prep

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#34]
Review and cleanup the license header in css.prep

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in css.prep:
```
css.prep/src/org/netbeans/modules/css/prep/ui/resources/style.less
css.prep/src/org/netbeans/modules/css/prep/ui/resources/style.scss
css.prep/test/qa-functional/data/css_prep/public_html/cc.less
css.prep/test/qa-functional/data/css_prep/public_html/cc.scss
css.prep/test/qa-functional/data/css_prep/public_html/folder/part.scss
css.prep/test/qa-functional/data/css_prep/public_html/folder/partial.less
css.prep/test/qa-functional/data/css_prep/public_html/less_syntax.less
css.prep/test/qa-functional/data/css_prep/public_html/sass_syntax.scss
css.prep/test/unit/data/testFiles/test.less
css.prep/test/unit/data/testFiles/testIssue227676.scss
css.prep/test/unit/data/testProject/public_html/client1.scss
css.prep/test/unit/data/testProject/public_html/lib1.scss
css.prep/test/unit/data/testProject/public_html/test.less
css.prep/test/unit/data/testProject/public_html/test1.scss
css.prep/test/unit/data/testProject/public_html/test2.scss

```

**Comment by tomazst** [comment]
I'll take this!
