### ISSUE TITLE
Cleanup NetBeans license header for module css.visual

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#35]
Review and cleanup the license header in css.visual

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in css.visual:
```
css.visual/src/org/netbeans/modules/css/visual/todo.txt
css.visual/test/qa-functional/data/CSSTestProject/build.xml
css.visual/test/qa-functional/data/CSSTestProject/nbproject/ant-deploy.xml
css.visual/test/qa-functional/data/CSSTestProject/src/conf/MANIFEST.MF
css.visual/test/qa-functional/data/CSSTestProject/web/WEB-INF/sun-web.xml
css.visual/test/qa-functional/data/CSSTestProject/web/WEB-INF/web.xml
css.visual/test/qa-functional/data/CSSTestProject/web/css/navigatorTest.css

```

**Comment by tomazst** [comment]
Can I work on this?

**Comment by emilianbold** [comment]
Sure!
