### ISSUE TITLE
Cleanup NetBeans license header for module dbschema

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#38]
Review and cleanup the license header in dbschema

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in dbschema:
```
dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/resources/templates/Database Schema.template
dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/resources/templates/Schema.template

```

**Comment by mohammedalics** [comment]
The two templates files are empty then perhaps we can exclude it in nbbuild/build.xml file ("rat" task), right?

**Comment by emilianbold** [comment]
Hm, I wonder why they are empty?

I think we can exclude them for now, but we should open a separate issue on issues.apache.org for NETBEANS and mention these files. My guess is they should be deleted.

**Comment by emilianbold** [comment]
@mohammedalics are you excluding those files on this issue?

**Comment by mohammedalics** [comment]
Unfortunately, I've not started yet. I can work on it by tomorrow.

**Comment by emilianbold** [comment]
Great!

**Comment by emilianbold** [comment]
@mohammedalics any update?

**Comment by emilianbold** [comment]
Hacktoberfest over. Good job everybody!
