### ISSUE TITLE
Cleanup NetBeans license header for module ant.freeform

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#4]
Review and cleanup the license header in ant.freeform

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in ant.freeform:
```
ant.freeform/test/unit/data/example-projects/extbuildroot/build/built.file
ant.freeform/test/unit/data/example-projects/extbuildscript/scripts/build.xml
ant.freeform/test/unit/data/example-projects/freeforminside/FreeForm/build.xml
ant.freeform/test/unit/data/example-projects/freeforminside/build.xml
ant.freeform/test/unit/data/example-projects/simple/build.properties
ant.freeform/test/unit/data/example-projects/simple/build.xml
ant.freeform/test/unit/data/example-projects/simple/src/org/foo/myapp/some-resource.txt
ant.freeform/test/unit/data/example-projects/simple/xdocs/foo.xml
ant.freeform/test/unit/data/example-projects/simple3/build.xml
ant.freeform/test/unit/data/example-projects/simplewithlicense/build.xml
ant.freeform/test/unit/data/example-projects/web_jakarta/build.properties
ant.freeform/test/unit/data/example-projects/web_jakarta/web/WEB-INF/web.xml
ant.freeform/test/unit/data/example-projects/web_jakarta/web/hello.jsp
ant.freeform/test/unit/data/example-projects/web_jakarta/web/index.html

```

**Comment by bjansen** [comment]
I'll give it a try :)

**Comment by emilianbold** [comment]
Closing this since `*/test/unit/data/**` is excluded globally so there is no Rat warning for this module anymore.
