### ISSUE TITLE
Cleanup NetBeans license header for module debugger.jpda

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#40]
Review and cleanup the license header in debugger.jpda

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in debugger.jpda:
```
debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/testapps/JspLineBreakpointApp.txt

```

**Comment by AnEmortalKid** [comment]
I volunteer to do this one.

**Comment by emilianbold** [comment]
Hm, I'm not certain that file works with a license header. Please select another issue.

**Comment by emilianbold** [comment]
*Or*, please investigate how that file is being used. It might be simpler to exclude it from nbbuild/build.xml ("rat" task).

**Comment by AnEmortalKid** [comment]
You might be right: 

https://github.com/apache/incubator-netbeans/blob/685504b42d44522d8feb2ad360975160648049c3/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/JspLineBreakpointTest.java#L41

I'll give a shot adding the license to it (but I'm also positive things will break). Depends on how long the travis build takes i'll give it a shot or not :)

**Comment by emilianbold** [comment]
Might be simpler to just exclude the file from "rat" task.

**Comment by AnEmortalKid** [comment]
Yeah I will do that. I added the license last night and my travis build
succeeded. I am reaaaaaaaaaaalllllllly skeptical so I'm going to exclude it
from rat :)

**Comment by AnEmortalKid** [comment]
cool, done.
