### ISSUE TITLE
Cleanup NetBeans license header for module editor.plain

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#49]
Review and cleanup the license header in editor.plain

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in editor.plain:
```
editor.plain/src/org/netbeans/modules/editor/plain/resources/PlainTextExample

```

**Comment by bjansen** [comment]
On it.

**Comment by emilianbold** [comment]
Please also take a look at cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review for the modules you pick.

The issues and the wiki (which is authoritative) sometimes get out of sync (since I have to do it manually).

Your PR might still be good though, I'll look into it later. Just a FYI

**Comment by bjansen** [comment]
OK, duly noted :)
