### ISSUE TITLE
Cleanup NetBeans license header for module html.custom

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#64]
Review and cleanup the license header in html.custom

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in html.custom:
```
html.custom/src/org/netbeans/modules/html/custom/spec.txt
html.custom/src/org/netbeans/modules/html/custom/todo.txt
html.custom/test/unit/data/testfiles/testHtmlApp/nbproject/customs.json
html.custom/test/unit/data/testfiles/testHtmlApp/public_html/index.html
html.custom/test/unit/data/testfiles/testHtmlApp/public_html/newjson.json

```

**Comment by isalopez-zz** [comment]
Hi! Can I work on this?

**Comment by emilianbold** [comment]
All yours. Updated https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

**Comment by emilianbold** [comment]
@suvreial any update?

**Comment by emilianbold** [comment]
@suvreial is no longer on this issue. Issue available for anybody.

**Comment by emilianbold** [comment]
Hacktoberfest over
