### ISSUE TITLE
Cleanup NetBeans license header for module html.editor.lib

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#65]
Review and cleanup the license header in html.editor.lib

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in html.editor.lib:
```
html.editor.lib/src/org/netbeans/modules/html/editor/lib/api/ProblemDescription.java
html.editor.lib/src/org/netbeans/modules/html/editor/lib/api/elements/Node.java
html.editor.lib/test/unit/data/input/HTMLCompletionQueryTest/index.html
html.editor.lib/test/unit/data/input/HTMLCompletionQueryTest/truncated_netbeans_front_page.html
html.editor.lib/test/unit/data/input/HTMLSyntaxSupportTest/index.html
html.editor.lib/test/unit/data/testfiles/syntaxtree/issues145821.html
html.editor.lib/test/unit/data/testfiles/syntaxtree/list.html
html.editor.lib/test/unit/data/testfiles/syntaxtree/missingEndTag.html
html.editor.lib/test/unit/data/testfiles/syntaxtree/table.html
html.editor.lib/test/unit/data/testfiles/syntaxtree/tagCrossing.html
html.editor.lib/test/unit/data/testfiles/syntaxtree/trivial.html

```

**Comment by martypowell** [comment]
@emilianbold I'll take this one.

**Comment by emilianbold** [comment]
@martypowell any updates?

**Comment by martypowell** [comment]
@emilianbold  See PR #300 ... if you end up need more help on these (aka hacktoberfest participants) I can do a couple more.
