### ISSUE TITLE
Cleanup NetBeans license header for module ide

### ISSUE THREAD

**Issue by emilianbold** [emilianbold/incubator-netbeans#78]
Review and cleanup the license header in ide

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in ide:
```
ide/launcher/macosx/NetBeansLauncher/English.lproj/MainMenu.nib/classes.nib
ide/launcher/macosx/NetBeansLauncher/English.lproj/MainMenu.nib/info.nib
ide/launcher/macosx/NetBeansLauncher/NetBeansLauncher.pbproj/project.pbxproj
ide/launcher/macosx/NetBeansLauncher/ReadMe.rtf
ide/launcher/netbeans.clusters
ide/launcher/netbeans.conf
ide/launcher/windows/.dep.inc
ide/projectopener/nbproject/configs/JWS_generated.properties
ide/projectopener/src/org/netbeans/projectopener/Bundle.properties

```

**Comment by ghost** [comment]
Working on

**Comment by ghost** [comment]
Done. PR #265

**Comment by emilianbold** [comment]
Note to self: I wonder if we shouldn't do something to ide/launcher/macosx/NetBeansLauncher/ReadMe.rtf

Not closing this yet to update the wiki.
